### ISSUE TITLE
小米6上面的一个问题

### ISSUE THREAD

**Issue by juanzhangzz** [wildma/PictureSelector#12]
小米6从相册选择后出现文件夹和相册选项,选择文件夹并选择某PNG图片,抛异常

**Comment by juanzhangzz** [comment]
异常内容：does not have permission to content://com.android.fileexplorer.myprovider/external_files/PictureSelector.temp.jpg

**Comment by wildma** [comment]
只有小米6才会吗？Android 版本是多少？

**Comment by juanzhangzz** [comment]
目前公司只有小米6出这个问题，华为的荣耀和mate都没有出问题
miui的版本：10.4.2
Android版本：9

**Comment by wildma** [comment]
已优化，还没发版本，可以下载源码测试下小米 6 中是否正常。

**Comment by JKXY** [comment]
看到这个，借楼说一句，之前测试，好像在相册选择图片，如果没有设置默认剪裁app,就会直接没有结果（具体是什么错误我也不知道，因为不是我测试的，是别人反馈给我的，在用相机拍照后是有选择剪裁app提示框的），测试机是小米8se

**Comment by wildma** [comment]
@JKXY demo 没发现这个问题，你可以测试下最新的 demo 看看。
