### ISSUE TITLE
android 10拍照问题

### ISSUE THREAD

**Issue by xuhang96** [wildma/PictureSelector#17]
android10拍照提示无法保存到相册

**Comment by Eclipse-Kio** [comment]
再清单文件Application标签下添加
android:requestLegacyExternalStorage ="true"

**Comment by wildma** [comment]
@xuhang96 最新版本已适配 Android Q。

**Comment by wildma** [comment]
@Eclipse-Kio 感谢回答！不过该属性只能暂时选择停用分区存储，因为后面官方要求所有应用都要使用分区存储，所以最终还是要适配 Android Q 的分区存储的。
