### ISSUE TITLE
库更新问题

### ISSUE THREAD

**Issue by dabai2017** [wildma/PictureSelector#19]
库每次更新后，在as必须要手动改最新版本号嘛。经常出问题

ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not download PictureSelector.aar (com.github.wildma:PictureSelector:1.1.4)
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not download PictureSelector.aar (com.github.wildma:PictureSelector:1.1.4)
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not download PictureSelector.aar (com.github.wildma:PictureSelector:1.1.4)
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@release/compileClasspath': Could not download PictureSelector.aar (com.github.wildma:PictureSelector:1.1.4)
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not download PictureSelector.aar (com.github.wildma:PictureSelector:1.1.4)
Show Details
Affected Modules: app

**Comment by wildma** [comment]
不需要，如果需要用最新的版本才需要改。
