### ISSUE TITLE
回调有问题

### ISSUE THREAD

**Issue by Qiaoshi96** [wildma/PictureSelector#2]
在fragment中拍照回掉，回到Activity上加载到第一个fragment了，我传的是当前fragment.this
手机三星5.0

**Comment by wildma** [comment]
你应该在当前Fragment中重写onActivityResult，而不是在Activity。

**Comment by wildma** [comment]
@Qiaoshi96 你应该在当前Fragment中重写onActivityResult，而不是在Activity。

**Comment by Qiaoshi96** [comment]
我是在当前fragment重写的，然后也走回调了，但是拍照（从相册选择不会）回来后会回到当前Activity的第一个fragment。

**Comment by wildma** [comment]
我这边测试是没问题的呢，而且就是一个普通的 startActivityForResult，你的跳转到其他 fragment 就有点奇怪了，你检查下你的代码。

**Comment by Qiaoshi96** [comment]
这个只是在5.0三星 型号SM-N9008s上才出现这个问题

**Comment by wildma** [comment]
@Qiaoshi96 那这就不知道你的具体是什么问题了~

**Comment by Qiaoshi96** [comment]
2642656099是否可以加QQ细聊
