### ISSUE TITLE
能不能增加一个无裁剪比例的方法

### ISSUE THREAD

**Issue by LijiangOP** [wildma/PictureSelector#24]
业务逻辑要求，需要个无裁剪比例的，看了下你的源码，没法实现，只能抽部分代码出来实现业务

**Comment by wildma** [comment]
你应该是需要自由裁剪的功能，最新版本已增加。使用如下：
```java
PictureSelector
		.create(MainActivity.this, PictureSelector.SELECT_REQUEST_CODE)
		.selectPicture(true);
```

如果你需要的是可以指定宽高，但是不需要裁剪比例。这个需求可以实现，但是裁剪出来的图片基本都是变形的。因为这样裁剪框无法根据指定的宽高按比例缩放，也就是裁剪框宽高与指定的宽高不是一个比例，最终裁剪出来的图片肯定是变形的。
