### ISSUE TITLE
能不能增加多语言

### ISSUE THREAD

**Issue by ericshi832** [wildma/PictureSelector#26]
老哥，库很好用，提两个想法，请考虑下
能不能增加几种常用国际化语言，中，英，繁，韩，日，
另外 能不能增加直接调用拍照的方法，不弹出选择
谢谢

**Comment by wildma** [comment]
不考虑增加多语言呢，不弹出选择你可以直接拷贝 PictureSelectUtils 类出来使用即可，后面有时间再改一下。
