### ISSUE TITLE
华为8.0nova2s 吊起相机拍照报：无法保存到相册

### ISSUE THREAD

**Issue by Qiaoshi96** [wildma/PictureSelector#5]
华为8.0nova2s 吊起相机拍照时报：无法保存到相册，大哥你这个有点坑啊

**Comment by Qiaoshi96** [comment]
这个问题我知道什么原因了：我写下载的的时候，修改了provider里面的authorities和你保存图片用到的不一样。你可以在博客里面指出来不然，不然这个bug太难找了

**Comment by wildma** [comment]
你应该是没有使用依赖的方式，而是直接拷贝我的源码到你的项目使用的。这样的话你就要自己考虑 Android 7.0 的适配了，也就是要使用 FileProvider 解决适配的问题。你的建议已加上，请在 Github 看最新的。
