### ISSUE TITLE
android9.0 data.getStringExtra为空

### ISSUE THREAD

**Issue by Liujiaohan** [wildma/PictureSelector#6]
data.getStringExtra(PictureSelector.PICTURE_PATH);

**Comment by Liujiaohan** [comment]
当设置为剪切的时候会返回空，不剪切的时候是正确的

**Comment by wildma** [comment]
我这边用华为 Android 9.0 测试是否裁剪都没遇到你说的问题呢，也可能是你那个特定机型有兼容性问题，现在我这里是复现不出该问题，如果你那边能解决欢迎PR。
